spring:
  application:
    name: spotguide-spring-boot
  jpa:
    hibernate.ddl-auto: create
#    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot?useSSL=false
    #url: jdbc:h2:mem:testdb
    username: sparky
    password: sparky123

  kafka:
    enabled: false
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

# There is an issue with `spring-cloud-starter-config`, when mixed with `spring-boot-starter-data-jpa` and `Spring Boot v2.1.x`.
# https://github.com/spring-cloud/spring-cloud-security/issues/143#issuecomment-376391930
spring.main.allow-bean-definition-overriding: true

management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.shutdown.enabled: true
endpoints.shutdown.enabled: true
