spring:
  application:
    name: spotguide-spring-boot
  jpa:
    hibernate.ddl-auto: create
#    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:h2:mem:testdb
#    username: sparky
#    password: sparky123
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management.endpoints.web.exposure.include: '*'
