# Default values for spotguide-java-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: banzaicloud/spotguide-spring-boot
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts: []
  #  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
    cpu: 1000m
    memory: 512Mi
   requests:
    cpu: 1000m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  mysqlUser: sparky
  mysqlPassword: sparky123
  mysqlDatabase: users
  metrics:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9104"
    livenessProbe:
      initialDelaySeconds: 200

kafka:
  enabled: false
  bootstrapServers: "kafka-headless.kafka:29092"

pipeline-ingress:
  enabled: false

pipeline-monitor:
  enabled: false
