pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.12
    action: EnsureCluster

  test:
    image: maven:3.6-jdk-11-slim
    commands:
    - mvn -Dmaven.repo.local=${PWD}/.m2/repository clean test

  build_image:
    image: maven:3.6-jdk-11-slim
    commands:
    - mvn -Dmaven.repo.local=${PWD}/.m2/repository compile jib:build
    environment:
      DOCKER_REPO: '{{ .CICD_REPO }}'
      DOCKER_TAG:  '{{ trunc 7 .CICD_COMMIT_SHA }}'
    secretFrom:
      DOCKER_USERNAME:
        keyRef: username
      DOCKER_PASSWORD:
        keyRef: password

#  build_image:
#    image: banzaicloud/drone-kaniko
#    dockerfile: Dockerfile
#    repo: '{{ .CICD_REPO }}'
#    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
#    secretFrom:
#      DOCKER_USERNAME:
#        keyRef: username
#      DOCKER_PASSWORD:
#        keyRef: password

#  install_gcr_secret:
#    when:
#      branch:
#        include: [master]
#    image: banzaicloud/ci-pipeline-client:0.12
#    action: InstallSecret
#    clusterSecret:
#      name: your-gcr-secret-name
#      namespace: default
#      merge: true
#      spec:
#        - name: json-key
#          source: json-key

#  build_image:
#    image: banzaicloud/drone-kaniko
#    dockerfile: Dockerfile
#    registry: gcr.io
#    repo: 'your-project/{{ .CICD_REPO }}'
#    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
#    secretFrom:
#      JSON_KEY:
#        name: your-gcr-secret-name
#        keyRef: json-key

  package_application:
    image: alpine/helm:3.0.0
    commands:
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
    - helm dep update ./.banzaicloud/charts/spotguide-spring-boot
    - helm package ./.banzaicloud/charts/spotguide-spring-boot

  install_mysql_user_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      merge: true
      spec:
        - name: mysql-username
          source: username
        - name: mysql-password
          source: password

  install_mysql_root_secret:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mysql'
      namespace: default
      merge: true
      spec:
        - name: mysql-root-password
          source: password

  deploy_application:
    when:
      branch:
        include: [master]
    image: banzaicloud/ci-pipeline-client:0.12
    action: EnsureDeployment
    deployment:
      name: './spotguide-spring-boot-1.0.0.tgz'
      reuseValues: true
      releaseName: '{{ .CICD_REPO_NAME }}'
      values:
        image:
          repository: '{{ .CICD_REPO }}'
          tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
          pullPolicy: Always
        {{{{- if .platform.AutoDNSEnabled }}}}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
            traefik.ingress.kubernetes.io/redirect-replacement: https://$1
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
          hosts:
          - "{{.CICD_REPO_NAME}}.{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}"
        {{{{ else }}}}
        service:
          type: LoadBalancer
        {{{{- end }}}}
        mysql:
          existingSecret: '{{ .CICD_REPO_NAME }}-mysql'
